spring.application.name=demo
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user1db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user1
spring.datasource.password=user1


# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
